// activity 1 

// let name = 'ben';
// let age = 21;
// let favcolour= 'blue'

// console.log('hi my name is ${name}.I am ${age}and my favourite colour is ${favcolour}.')


// activity 2 

// let num = 10 ;

// if num =(num%3){
// console.log ('fizz');

// }else num =(num%5){
// console.log('buzz');

// }else if (num/5||num){
// console.log ('fizz,buzz')};




// activity  3


// let favFilms =['avatar','nemo','shrek','hulk','gladiator']

// favFilms.push('ironman')
// favFilms.push('pulp fiction ')

// for (let i=0;i<favFilms.length; i ++){
//     console.log(favFilms[i])
// }

